const match={home:"南非",away:"加拿大",homeFlag:"🇿🇦",awayFlag:"🇨🇦",group:"32强",venue:"洛杉矶 SoFi · 13:00 PT",rankH:59,rankA:28,recordH:"A组第二",recordA:"B组第二",stage:"knockout",coachH:["雨果·布鲁斯",3,1,1,1],coachA:["杰西·马什",3,1,1,1],odds:[4.10,3.25,1.92],statusH:"A组第二晋级，淘汰赛90分钟先求低失误",statusA:"B组第二晋级，阵容深度略好但离开本土主场",bracket:"官方赛程口径：A组第二 vs B组第二，比赛地为洛杉矶 SoFi。淘汰赛没有平局晋级结果，本页先模拟90分钟，平局样本再进入点球子模拟。",path:"已结束小组赛结果只做轻量校准：强队控场胜与低比分卡位战并存，因此今日总进球均值小幅下调、0:0/1:1权重维持。项目内同源赔率快照没有本场盘口；伤停、裁判样本、官方教练逐场数据和可审计社媒比分样本均未完整接入，暂不作为数值输入。",attackH:1.02,defenseH:1.04,attackA:1.32,defenseA:.95,formH:6,formA:7,goalCorrelation:.19,penaltyEdgeH:-.01,penaltyEdgeA:.03};
const matches=[match];let simulationEpoch=0;const $=id=>document.getElementById(id);const fact=n=>n<=1?1:n*fact(n-1);const pois=(g,l)=>Math.exp(-l)*Math.pow(l,g)/fact(g);const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function rng(seed){let s=seed>>>0;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function gauss(r){const u=Math.max(r(),1e-9),v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function samplePois(l,r){const lim=Math.exp(-l);let p=1,c=0;do{c++;p*=r()}while(p>lim&&c<12);return c-1}
function sampleBi(h,a,corr,r){const common=clamp(corr,0,.35)*Math.min(h,a);return{h:samplePois(Math.max(.01,h-common),r)+samplePois(common,r),a:samplePois(Math.max(.01,a-common),r)+samplePois(common,r)}}
function dc(h,a,lh,la,rho){if(h===0&&a===0)return 1-lh*la*rho;if(h===0&&a===1)return 1+lh*rho;if(h===1&&a===0)return 1+la*rho;if(h===1&&a===1)return 1-rho;return 1}
function lowDraw(h,a,lh,la,rho){const b=dc(h,a,lh,la,rho);if(h===0&&a===0)return b*1.225;if(h===1&&a===1)return b*1.18;return b}
function baseXg(hf=match.formH,af=match.formA,tempo=5){const fH=1+(hf-5.5)*.018,fA=1+(af-5.5)*.018,tf=.82+tempo*.036,rank=clamp((match.rankA-match.rankH)*.002,-.12,.12);let h=match.attackH*match.defenseA*fH*tf*1.08*(1+rank)*1.004;let a=match.attackA*match.defenseH*fA*tf*(1-rank)*1.004;const total=h+a,adj=Math.max(.7,total-.08);h*=adj/total;a*=adj/total;return{h:clamp(h,.25,3.5),a:clamp(a,.2,3.2)}}
function monteCarlo(hf,af,tempo,runs=50000,seed=20260629,rho=-.08,crowd=null){const b=baseXg(hf,af,tempo),r=rng(seed),scores=new Map(),totals=new Map();let hw=0,d=0,aw=0,ha=0,aa=0,tw=0,gh=0,ga=0;for(let i=0;i<runs;i++){const shock=Math.exp(.18*gauss(r)-.5*.18**2);let lh=b.h*shock*Math.exp(.12*gauss(r)-.5*.12**2),la=b.a*shock*Math.exp(.12*gauss(r)-.5*.12**2);if(r()<.34){lh*=.92;la*=.92}const s=sampleBi(Math.min(lh,4.8),Math.min(la,4.8),match.goalCorrelation,r),key=`${s.h}:${s.a}`;let w=Math.max(.05,lowDraw(s.h,s.a,lh,la,rho));if(crowd?.enabled&&key===crowd.score)w*=1-crowd.penalty;tw+=w;gh+=s.h*w;ga+=s.a*w;if(s.h>s.a){hw+=w;ha+=w}else if(s.h===s.a){d+=w;const p=clamp(.5+((50-match.rankH)-(50-match.rankA))/220+match.penaltyEdgeH-match.penaltyEdgeA,.38,.62);if(r()<p)ha+=w;else aa+=w}else{aw+=w;aa+=w}scores.set(key,(scores.get(key)||0)+w);totals.set(s.h+s.a,(totals.get(s.h+s.a)||0)+w)}const topScores=[...scores.entries()].sort((a,b)=>b[1]-a[1]).slice(0,4).map(([score,c])=>({score,probability:c/tw}));const topTotals=[...totals.entries()].sort((a,b)=>b[1]-a[1]).slice(0,2).map(([goals,c])=>({goals,probability:c/tw}));const [hs,as]=topScores[0].score.split(":").map(Number);const probs=[hw/tw,d/tw,aw/tw],sort=[...probs].sort((a,b)=>b-a);return{homeWin:probs[0],draw:probs[1],awayWin:probs[2],homeAdvance:ha/tw,awayAdvance:aa/tw,homeXg:gh/tw,awayXg:ga/tw,best:{h:hs,a:as},topScores,topTotals,scoreProbabilities:Object.fromEntries([...scores.entries()].map(([k,c])=>[k,c/tw])),confidence:Math.min(88,Math.round(48+(sort[0]-sort[1])*60)),runs}}
function wdl(r){const arr=[['主胜',r.homeWin],['平局',r.draw],['客胜',r.awayWin]].sort((a,b)=>b[1]-a[1]);return{label:arr[0][0],probability:arr[0][1],note:arr[0][1]-arr[1][1]<.06?'分歧较小，谨慎':'模型最高概率'}}
function hand(r){const lines=[-2,-1.5,-1,-.5,.5,1,1.5,2],cs=[];for(const side of['home','away'])for(const line of lines){let cover=0;for(const[k,p]of Object.entries(r.scoreProbabilities)){const[x,y]=k.split(':').map(Number),m=side==='home'?x-y:y-x;if(m+line>0)cover+=p}const useful=cover>=.54&&cover<=.82,score=(useful?.08:0)+cover-Math.abs(cover-.64)-(Math.abs(line)>=2?.04:Math.abs(line)>=1.5?.02:0);cs.push({side,line,cover,score})}cs.sort((a,b)=>b.score-a.score);const p=cs[0],team=p.side==='home'?match.home:match.away;return{label:`${team} ${p.line>0?'+':''}${p.line}`,probability:p.cover,note:p.cover>=.7?'保护垫较厚':'模型覆盖率最高'}}
function market(probs,odds){const raw=odds.map(o=>1/o),over=raw.reduce((a,b)=>a+b,0),m=raw.map(v=>v/over);return{market:m,edges:probs.map((p,i)=>p-m[i]),kelly:probs.map((p,i)=>Math.max(0,(p*odds[i]-1)/(odds[i]-1))),overround:over-1}}
function setOdds(odds){['oddsHome','oddsDraw','oddsAway'].forEach((id,i)=>$(id).value=odds[i].toFixed(2))}
function renderMarket(a,model){const labels=['主胜','平局','客胜'];$('marketMargin').textContent=`市场水位 ${(a.overround*100).toFixed(1)}%`;$('marketRows').innerHTML=labels.map((l,i)=>{const e=a.edges[i]*100,cls=e>0?'positive':e<0?'negative':'';return`<div><strong>${l}</strong><span>${(model[i]*100).toFixed(1)}%</span><span>${(a.market[i]*100).toFixed(1)}%</span><span class="${cls}">${e>=0?'+':''}${e.toFixed(1)}pp</span><span>${(a.kelly[i]*100).toFixed(1)}%</span></div>`}).join('')}
function reason(r,hf,af,tempo){const fav=r.homeWin>r.awayWin?match.home:match.away,edge=Math.abs(r.homeXg-r.awayXg),state=edge>.8?'优势明显':edge>.3?'略占上风':'实力非常接近',rhythm=tempo>=7?'比赛节奏偏开放':tempo<=3?'比赛可能谨慎展开，低比分权重更高':'节奏预计适中';return`${fav}在模型中${state}，${rhythm}。赛制背景：${match.statusH}；${match.statusA}。${match.path} 淘汰赛路径：${match.bracket} 本场按淘汰赛分层，90分钟平局后会嵌套点球子模拟；晋级概率为 ${match.home} ${(r.homeAdvance*100).toFixed(1)}%，${match.away} ${(r.awayAdvance*100).toFixed(1)}%。经过 ${r.runs.toLocaleString('zh-CN')} 次赛况抽样，最高频比分为 ${r.best.h}:${r.best.a}。`}
function renderCards(){const r=monteCarlo(match.formH,match.formA,5);$('matchGrid').innerHTML=`<button class="match-card active" data-index="0"><div class="match-meta"><span>${match.group} · ${match.venue}</span><span>M1</span></div><div class="fixture-teams"><div class="fixture-team"><span>${match.homeFlag} ${match.home}</span><small>#${match.rankH} · ${match.recordH}</small></div><div class="fixture-team"><span>${match.awayFlag} ${match.away}</span><small>#${match.rankA} · ${match.recordA}</small></div></div><div class="card-prediction"><small>蒙特卡洛首选</small><span class="mini-score">${r.best.h}:${r.best.a}</span></div></button>`}
function updateContext(){$('homeRank').textContent=`世界 #${match.rankH}`;$('awayRank').textContent=`世界 #${match.rankA}`;$('homeSituation').textContent=`${match.recordH} · ${match.statusH}`;$('awaySituation').textContent=`${match.recordA} · ${match.statusA}`;$('pathText').textContent=match.path;$('bracketText').textContent=match.bracket;$('homeCoach').textContent=match.coachH[0];$('awayCoach').textContent=match.coachA[0];$('homeCoachRecord').textContent=`${match.coachH[2]}胜 ${match.coachH[3]}平 ${match.coachH[4]}负`;$('awayCoachRecord').textContent=`${match.coachA[2]}胜 ${match.coachA[3]}平 ${match.coachA[4]}负`}
function syncOutputs(){$('homeFormOutput').textContent=$('homeForm').value;$('awayFormOutput').textContent=$('awayForm').value;$('tempoOutput').textContent=$('tempo').value}
function updatePrediction(){const hf=+$('homeForm').value,af=+$('awayForm').value,tempo=+$('tempo').value,rho=+$('rho').value/100,crowd={enabled:$('crowdMode').checked,score:`${+$('crowdHome').value||0}:${+$('crowdAway').value||0}`,penalty:+$('crowdPenalty').value/100},r=monteCarlo(hf,af,tempo,50000,20260629+simulationEpoch*7919+hf*31+af*17+tempo,rho,crowd),w=wdl(r),h=hand(r),m=market([r.homeWin,r.draw,r.awayWin],['oddsHome','oddsDraw','oddsAway'].map(id=>Math.max(1.01,+$(id).value||2)));$('homeScore').textContent=r.best.h;$('awayScore').textContent=r.best.a;$('predictionType').textContent='蒙特卡洛综合预测';$('homeWin').textContent=`${Math.round(r.homeWin*100)}%`;$('draw').textContent=`${Math.round(r.draw*100)}%`;$('awayWin').textContent=`${Math.round(r.awayWin*100)}%`;$('wdlPick').textContent=w.label;$('wdlPickNote').textContent=`${w.note} · ${(w.probability*100).toFixed(1)}%`;$('handicapPick').textContent=h.label;$('handicapPickNote').textContent=`${h.note} · ${(h.probability*100).toFixed(1)}%`;$('confidence').textContent=`置信度 ${r.confidence}%`;$('reason').textContent=reason(r,hf,af,tempo);$('xgText').textContent=`${r.homeXg.toFixed(2)} — ${r.awayXg.toFixed(2)}`;$('simulationCount').textContent=`${r.runs.toLocaleString('zh-CN')} 次模拟`;$('rhoOutput').textContent=rho.toFixed(2);$('crowdPenaltyOutput').textContent=`${Math.round(crowd.penalty*100)}%`;$('topScores').innerHTML=r.topScores.map((x,i)=>`<span><i>${i+1}</i>${x.score}<small>${(x.probability*100).toFixed(1)}%</small></span>`).join('');$('topTotals').innerHTML=r.topTotals.map((x,i)=>`<span><i>${i+1}</i><strong>${x.goals} 球</strong><small>${(x.probability*100).toFixed(1)}%</small></span>`).join('');const t=r.homeXg+r.awayXg;$('homeXgBar').style.width=`${r.homeXg/t*100}%`;$('awayXgBar').style.width=`${r.awayXg/t*100}%`;renderMarket(m,[r.homeWin,r.draw,r.awayWin])}
['homeForm','awayForm','tempo'].forEach(id=>$(id).addEventListener('input',syncOutputs));['rho','oddsHome','oddsDraw','oddsAway','crowdHome','crowdAway','crowdPenalty'].forEach(id=>$(id).addEventListener('input',updatePrediction));$('crowdMode').addEventListener('change',updatePrediction);$('predictButton').addEventListener('click',()=>{simulationEpoch++;updatePrediction()});$('aboutButton').addEventListener('click',()=>$('aboutDialog').showModal());$('closeDialog').addEventListener('click',()=>$('aboutDialog').close());$('aboutDialog').addEventListener('click',e=>{if(e.target===$('aboutDialog'))$('aboutDialog').close()});$('homeFlag').textContent=match.homeFlag;$('awayFlag').textContent=match.awayFlag;$('homeName').textContent=match.home;$('awayName').textContent=match.away;$('homeForm').value=match.formH;$('awayForm').value=match.formA;setOdds(match.odds);updateContext();syncOutputs();renderCards();updatePrediction();