const matches=[
{home:'西班牙',away:'奥地利',homeFlag:'🇪🇸',awayFlag:'🇦🇹',group:'32强 · 7/2待赛',venue:'Polymarket 07/03 03:00',rankH:4,rankA:22,recordH:'晋级32强',recordA:'晋级32强',stage:'knockout',homeAdvantage:1,attackH:1.76,defenseH:.76,attackA:1.24,defenseA:.96,formH:8,formA:6,coachH:['西班牙教练组',10,7,2,1],coachA:['奥地利教练组',10,5,3,2],statusH:'控球与压迫结构优势明显',statusA:'整体压迫和定位球存在扰动',path:'赛程写法 Spain vs Austria；中立场不默认主场优势。已接入 HKJC 与 Polymarket 截图价格。',bracket:'淘汰赛：先模拟90分钟，若平局再触发点球大战子模拟。'},
{home:'葡萄牙',away:'克罗地亚',homeFlag:'🇵🇹',awayFlag:'🇭🇷',group:'32强 · 7/2待赛',venue:'Polymarket 07/03 07:00',rankH:6,rankA:18,recordH:'晋级32强',recordA:'晋级32强',stage:'knockout',homeAdvantage:1,attackH:1.66,defenseH:.82,attackA:1.30,defenseA:.90,formH:8,formA:7,coachH:['葡萄牙教练组',10,7,2,1],coachA:['克罗地亚教练组',10,5,3,2],statusH:'前场终结和阵容深度占优',statusA:'经验和中场控制能拖入胶着局',path:'赛程写法 Portugal vs Croatia；中立场不默认主场优势。已接入 HKJC 与 Polymarket 截图价格。',bracket:'淘汰赛：强弱差距被90分钟平局和点球尾部收缩。'},
{home:'瑞士',away:'阿尔及利亚',homeFlag:'🇨🇭',awayFlag:'🇩🇿',group:'32强 · 7/2待赛',venue:'Polymarket 07/03 11:00',rankH:19,rankA:38,recordH:'晋级32强',recordA:'晋级32强',stage:'knockout',homeAdvantage:1,attackH:1.28,defenseH:.90,attackA:1.16,defenseA:.98,formH:6,formA:6,coachH:['瑞士教练组',10,5,3,2],coachA:['阿尔及利亚教练组',10,5,2,3],statusH:'防守组织和定位球稳定',statusA:'边路速度和反击威胁明显',path:'赛程写法 Switzerland vs Algeria；中立场不默认主场优势。Polymarket 显示阿尔及利亚让分受让侧更受保护。',bracket:'接近局提高1:1与点球分支权重。'},
{home:'阿根廷',away:'佛得角',homeFlag:'🇦🇷',awayFlag:'🇨🇻',group:'32强 · 7/3待赛',venue:'Polymarket 07/04 06:00',rankH:1,rankA:66,recordH:'晋级32强',recordA:'晋级32强',stage:'knockout',homeAdvantage:1,attackH:1.92,defenseH:.70,attackA:.82,defenseA:1.18,formH:9,formA:5,coachH:['阿根廷教练组',10,8,1,1],coachA:['佛得角教练组',10,4,3,3],statusH:'冠军级阵容和控场能力明显占优',statusA:'低位防守和定位球是主要机会',path:'赛程写法 Argentina vs Cabo Verde；中立场不默认主场优势。Polymarket 交易量较高但权重封顶5%。',bracket:'强热门仍做贝叶斯收缩，避免热门过热。'},
{home:'澳大利亚',away:'埃及',homeFlag:'🇦🇺',awayFlag:'🇪🇬',group:'32强 · 7/3待赛',venue:'Polymarket 07/04 02:00',rankH:26,rankA:35,recordH:'晋级32强',recordA:'晋级32强',stage:'knockout',homeAdvantage:1,attackH:1.18,defenseH:.98,attackA:1.22,defenseA:.96,formH:6,formA:6,coachH:['澳大利亚教练组',10,5,3,2],coachA:['埃及教练组',10,5,3,2],statusH:'身体对抗和定位球稳定',statusA:'反击和个人终结能力具备上限',path:'赛程写法 Australia vs Egypt；中立场不默认主场优势。Polymarket 大小球线为1.5，提示低总进球压力。',bracket:'实力接近，90分钟平局权重提高。'},
{home:'哥伦比亚',away:'加纳',homeFlag:'🇨🇴',awayFlag:'🇬🇭',group:'32强 · 7/3待赛',venue:'Polymarket 07/04 09:30',rankH:12,rankA:52,recordH:'晋级32强',recordA:'晋级32强',stage:'knockout',homeAdvantage:1,attackH:1.46,defenseH:.86,attackA:1.02,defenseA:1.08,formH:7,formA:5,coachH:['哥伦比亚教练组',10,6,3,1],coachA:['加纳教练组',10,4,3,3],statusH:'中前场创造力和转换质量占优',statusA:'身体强度和纵深冲击存在冷门空间',path:'赛程写法 Colombia vs Ghana；中立场不默认主场优势。Polymarket 对哥伦比亚方向较集中。',bracket:'热门方向保留，但让分保护提示需防小胜。'},
{home:'加拿大',away:'摩洛哥',homeFlag:'🇨🇦',awayFlag:'🇲🇦',group:'32强 · 7/4待赛',venue:'HKJC 07/05 01:00',rankH:31,rankA:12,recordH:'晋级32强',recordA:'晋级32强',stage:'knockout',homeAdvantage:1,attackH:1.14,defenseH:.98,attackA:1.38,defenseA:.82,formH:6,formA:7,coachH:['加拿大教练组',10,5,2,3],coachA:['摩洛哥教练组',10,6,3,1],statusH:'身体对抗和转换速度有威胁',statusA:'防守结构、边路速度和点球韧性更受市场认可',path:'HKJC 与 Polymarket 均显示 Canada vs Morocco；中立场不默认主场优势。',bracket:'摩洛哥为市场方向，但淘汰赛保留平局尾部。'},
{home:'巴拉圭',away:'法国',homeFlag:'🇵🇾',awayFlag:'🇫🇷',group:'16强 · 7/4待赛',venue:'HKJC 07/05 05:00',rankH:48,rankA:2,recordH:'晋级16强',recordA:'晋级16强',stage:'knockout',homeAdvantage:1,attackH:.96,defenseH:1.06,attackA:1.88,defenseA:.74,formH:6,formA:8,coachH:['巴拉圭教练组',10,4,3,3],coachA:['法国教练组',10,7,2,1],statusH:'点球晋级后防守和拖慢节奏是核心路径',statusA:'个人能力、阵容深度和转换质量明显占优',path:'HKJC 与 Polymarket 均显示 Paraguay vs France；中立场不默认主场优势。',bracket:'法国极热，模型用贝叶斯收缩和低比分修正防过热。'},
{home:'巴西',away:'挪威',homeFlag:'🇧🇷',awayFlag:'🇳🇴',group:'16强 · 7/5待赛',venue:'HKJC 07/06 04:00',rankH:5,rankA:24,recordH:'晋级16强',recordA:'晋级16强',stage:'knockout',homeAdvantage:1,attackH:1.84,defenseH:.78,attackA:1.54,defenseA:.90,formH:8,formA:7,coachH:['巴西教练组',10,6,2,2],coachA:['挪威教练组',10,6,2,2],statusH:'前场创造力和压迫上限更高',statusA:'上一轮2–1晋级，反击效率和身体对抗会让比赛更开放',path:'HKJC 与 Polymarket 均显示 Brazil vs Norway；中立场不默认主场优势。',bracket:'巴西方向占优，但挪威进球尾部上调。'}
];
const marketOddsBook={'西班牙|奥地利':{odds:[1.25,4.45,9.75],source:'香港马会胜平负',checkedAt:'2026-07-01 18:17 HKT'},'葡萄牙|克罗地亚':{odds:[1.59,3.30,5.00],source:'香港马会胜平负',checkedAt:'2026-07-01 18:17 HKT'},'瑞士|阿尔及利亚':{odds:[1.84,2.97,4.00],source:'香港马会胜平负',checkedAt:'2026-07-01 18:17 HKT'},'澳大利亚|埃及':{odds:[3.15,2.67,2.29],source:'香港马会胜平负',checkedAt:'2026-07-01 18:17 HKT'},'阿根廷|佛得角':{odds:[1.09,6.30,17.00],source:'香港马会胜平负',checkedAt:'2026-07-01 18:17 HKT'},'哥伦比亚|加纳':{odds:[1.37,3.70,7.50],source:'香港马会胜平负',checkedAt:'2026-07-01 18:17 HKT'},'加拿大|摩洛哥':{odds:[5.20,3.05,1.64],source:'香港马会胜平负',checkedAt:'2026-07-01 18:17 HKT'},'巴拉圭|法国':{odds:[14.00,6.25,1.11],source:'香港马会胜平负',checkedAt:'2026-07-01 18:17 HKT'},'巴西|挪威':{odds:[1.74,3.20,4.10],source:'香港马会胜平负',checkedAt:'2026-07-01 18:17 HKT'}};
const predictionMarketBook={'西班牙|奥地利':{probabilities:[.75,.18,.08],volumeUsd:3070000,source:'Polymarket World Cup',checkedAt:'2026-07-02 截图读取'},'葡萄牙|克罗地亚':{probabilities:[.56,.27,.1875],volumeUsd:2450000,source:'Polymarket World Cup',checkedAt:'2026-07-02 截图读取'},'瑞士|阿尔及利亚':{probabilities:[.4775,.30,.2325],volumeUsd:763390,source:'Polymarket World Cup',checkedAt:'2026-07-02 截图读取'},'澳大利亚|埃及':{probabilities:[.29,.34,.39],volumeUsd:384170,source:'Polymarket World Cup',checkedAt:'2026-07-02 截图读取'},'阿根廷|佛得角':{probabilities:[.85,.12,.044],volumeUsd:2740000,source:'Polymarket World Cup',checkedAt:'2026-07-02 截图读取'},'哥伦比亚|加纳':{probabilities:[.65,.25,.13],volumeUsd:542720,source:'Polymarket World Cup',checkedAt:'2026-07-02 截图读取'},'加拿大|摩洛哥':{probabilities:[.19,.28,.55],volumeUsd:1100000,source:'Polymarket World Cup',checkedAt:'2026-07-02 截图读取'},'巴拉圭|法国':{probabilities:[.05,.13,.84],volumeUsd:474190,source:'Polymarket World Cup',checkedAt:'2026-07-02 截图读取'},'巴西|挪威':{probabilities:[.52,.27,.22],volumeUsd:432950,source:'Polymarket World Cup',checkedAt:'2026-07-02 截图读取'}};
let selectedIndex=0,simulationEpoch=0;const $=id=>document.getElementById(id),key=m=>`${m.home}|${m.away}`,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function formatVolume(v){return v>=1e6?(v/1e6).toFixed(2)+'M':v>=1e3?(v/1e3).toFixed(0)+'K':Math.round(v)}
function rng(seed){let s=seed>>>0;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function samplePoisson(l,r){let L=Math.exp(-l),p=1,k=0;do{k++;p*=r()}while(p>L&&k<12);return k-1}
function xg(m,h=m.formH,a=m.formA,t=5){let tempo=.82+t*.036,rank=clamp((m.rankA-m.rankH)*.002,-.12,.12);let hx=clamp(m.attackH*m.defenseA*(1+(h-5.5)*.02)*tempo*(m.homeAdvantage||1)*(1+rank),.25,3.5);let ax=clamp(m.attackA*m.defenseH*(1+(a-5.5)*.02)*tempo*(1-rank),.2,3.2);return[hx,ax]}
function simulate(m,h=m.formH,a=m.formA,t=5,rho=-.08,crowd=null,runs=50000,seed=20260702){let[baseH,baseA]=xg(m,h,a,t),r=rng(seed),score={},tot={},hw=0,d=0,aw=0,ha=0,aa=0,th=0,ta=0,wSum=0;for(let i=0;i<runs;i++){let tight=m.stage==='knockout'?.92:1,gh=samplePoisson(baseH*tight,r),ga=samplePoisson(baseA*tight,r),key=`${gh}:${ga}`,w=1;if((gh===0&&ga===0)||(gh===1&&ga===1))w*=1.2;if(crowd?.enabled&&key===crowd.score)w*=1-crowd.penalty;score[key]=(score[key]||0)+w;tot[gh+ga]=(tot[gh+ga]||0)+w;wSum+=w;th+=gh*w;ta+=ga*w;if(gh>ga){hw+=w;ha+=w}else if(gh<ga){aw+=w;aa+=w}else{d+=w;let p=clamp(.5+(m.rankA-m.rankH)/420,.40,.60);r()<p?ha+=w:aa+=w}}let topScores=Object.entries(score).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([s,c])=>({score:s,probability:c/wSum}));let topTotals=Object.entries(tot).sort((a,b)=>b[1]-a[1]).slice(0,2).map(([g,c])=>({goals:g,probability:c/wSum}));let best=topScores[0].score.split(':').map(Number),probs=[hw/wSum,d/wSum,aw/wSum].sort((a,b)=>b-a);return{homeWin:hw/wSum,draw:d/wSum,awayWin:aw/wSum,homeAdvance:ha/wSum,awayAdvance:aa/wSum,homeXg:th/wSum,awayXg:ta/wSum,best:{h:best[0],a:best[1]},topScores,topTotals,confidence:Math.min(88,Math.round(48+(probs[0]-probs[1])*60)),runs,scoreProbabilities:Object.fromEntries(Object.entries(score).map(([s,c])=>[s,c/wSum]))}}
function marketAnalysis(p,o){let raw=o.map(x=>1/x),sum=raw.reduce((a,b)=>a+b,0),market=raw.map(x=>x/sum);return{market,edges:p.map((x,i)=>x-market[i]),kelly:p.map((x,i)=>Math.max(0,(x*o[i]-1)/(o[i]-1))),overround:sum-1}}
function blendMarket(r,a){if(!a)return r;let w=clamp(.18-Math.max(0,a.overround-.1)*.6,.10,.18),b={...r,homeWin:r.homeWin*(1-w)+a.market[0]*w,draw:r.draw*(1-w)+a.market[1]*w,awayWin:r.awayWin*(1-w)+a.market[2]*w,marketPriorWeight:w};let s=[b.homeWin,b.draw,b.awayWin].sort((x,y)=>y-x);b.confidence=Math.min(88,Math.round(48+(s[0]-s[1])*60));return b}
function pmAnalysis(m){let b=predictionMarketBook[key(m)];if(!b)return null;let raw=b.probabilities.map(x=>Math.max(0,x)),sum=raw.reduce((a,b)=>a+b,0),market=raw.map(x=>x/sum),s=[...market].sort((a,b)=>b-a),conc=s[0]-s[1],liq=clamp(Math.log10(Math.max(b.volumeUsd,1)/250000),0,1.2),weight=clamp(.018+liq*.012+conc*.025,.018,.05);return{market,weight,source:`${b.source} · ${b.checkedAt} · 交易量 $${formatVolume(b.volumeUsd)}`}}
function blendPm(r,a){if(!a)return r;let b={...r,homeWin:r.homeWin*(1-a.weight)+a.market[0]*a.weight,draw:r.draw*(1-a.weight)+a.market[1]*a.weight,awayWin:r.awayWin*(1-a.weight)+a.market[2]*a.weight,predictionMarketWeight:a.weight,predictionMarketSource:a.source};let s=[b.homeWin,b.draw,b.awayWin].sort((x,y)=>y-x);b.confidence=Math.min(88,Math.round(48+(s[0]-s[1])*60));return b}
function odds(m){return marketOddsBook[key(m)]?.odds||null}function oddsSource(m){let b=marketOddsBook[key(m)];return b?`${b.source} · ${b.checkedAt}`:'本地赔率快照'}
function ranked(){return matches.map((m,index)=>({match:m,index,preview:simulate(m,m.formH,m.formA,5,-.08,null,12000,20260624+index*997)})).sort((a,b)=>b.preview.confidence-a.preview.confidence||a.index-b.index)}
function coach(c){let[n,mt,w,d,l]=c;return{name:n,wins:w,draws:d,losses:l}}
function reason(m,r,adj){let fav=adj.homeWin>adj.awayWin?m.home:m.away,edge=Math.abs(r.homeXg-r.awayXg),state=edge>.8?'优势明显':edge>.3?'略占上风':'实力接近';let note=`${fav}在模型中${state}。赛制背景：${m.statusH}；${m.statusA}。${m.path} ${m.bracket} 已加入双变量泊松、Dixon–Coles低比分修正、贝叶斯收缩与中立场主场校验。经过 ${r.runs.toLocaleString('zh-CN')} 次赛况抽样，最高频比分为 ${r.best.h}:${r.best.a}。`;if(adj.marketPriorWeight)note+=` 已融合${oddsSource(m)}去水概率作为${Math.round(adj.marketPriorWeight*100)}%权重的市场先验。`;if(adj.predictionMarketWeight)note+=` 已融合${adj.predictionMarketSource}作为${Math.round(adj.predictionMarketWeight*100)}%权重的资金共识先验；价格按钮不等于逐队真实成交量。`;return note}
function recWdl(m,r){let arr=[['主胜',r.homeWin],['平局',r.draw],['客胜',r.awayWin]].sort((a,b)=>b[1]-a[1]);return{label:arr[0][0],probability:arr[0][1],note:arr[0][1]-arr[1][1]<.06?'分歧较小，谨慎':'模型最高概率'}}
function recHandicap(m,r){let lines=[-2,-1.5,-1,-.5,.5,1,1.5,2],c=[];for(let side of ['home','away'])for(let line of lines){let cover=0;for(let[sc,p]of Object.entries(r.scoreProbabilities)){let[h,a]=sc.split(':').map(Number),margin=side==='home'?h-a:a-h;if(margin+line>0)cover+=p}c.push({side,line,cover,score:cover-Math.abs(cover-.64)-(Math.abs(line)>=2?.04:Math.abs(line)>=1.5?.02:0)})}c.sort((a,b)=>b.score-a.score);let p=c[0],team=p.side==='home'?m.home:m.away;return{label:`${team} ${p.line>0?'+':''}${p.line}`,probability:p.cover,note:p.cover>=.70?'保护垫较厚':'模型覆盖率最高'}}
function renderCards(){let es=ranked();$('matchGrid').innerHTML=es.map(({match:m,index:i,preview:r})=>`<button class="match-card ${i===selectedIndex?'active':''}" data-index="${i}"><div class="match-meta"><span>${m.group} · ${m.venue}</span><span>M${i+1}</span></div><div class="fixture-teams"><div class="fixture-team"><span>${m.homeFlag} ${m.home}</span><small>#${m.rankH} · ${m.recordH}</small></div><div class="fixture-team"><span>${m.awayFlag} ${m.away}</span><small>#${m.rankA} · ${m.recordA}</small></div></div><div class="card-prediction"><small>蒙特卡洛首选 · 置信度 ${r.confidence}%</small><span class="mini-score">${r.best.h}:${r.best.a}</span></div></button>`).join('');document.querySelectorAll('.match-card').forEach(c=>c.addEventListener('click',()=>selectMatch(+c.dataset.index)))}
function setOdds(m){(odds(m)||[2,3.2,2]).forEach((v,i)=>$(['oddsHome','oddsDraw','oddsAway'][i]).value=v.toFixed(2))}
function updateContext(m){$('homeRank').textContent=`世界 #${m.rankH}`;$('awayRank').textContent=`世界 #${m.rankA}`;$('homeSituation').textContent=`${m.recordH} · ${m.statusH}`;$('awaySituation').textContent=`${m.recordA} · ${m.statusA}`;$('pathText').textContent=m.path;$('bracketText').textContent=m.bracket;let h=coach(m.coachH),a=coach(m.coachA);$('homeCoach').textContent=h.name;$('awayCoach').textContent=a.name;$('homeCoachRecord').textContent=`${h.wins}胜 ${h.draws}平 ${h.losses}负`;$('awayCoachRecord').textContent=`${a.wins}胜 ${a.draws}平 ${a.losses}负`;$('homeCoachRate').textContent='首版整理值 · 待逐场复核，暂不入模';$('awayCoachRate').textContent='首版整理值 · 待逐场复核，暂不入模'}
function selectMatch(i){selectedIndex=i;let m=matches[i];$('homeFlag').textContent=m.homeFlag;$('awayFlag').textContent=m.awayFlag;$('homeName').textContent=m.home;$('awayName').textContent=m.away;$('homeForm').value=m.formH;$('awayForm').value=m.formA;$('tempo').value=5;setOdds(m);updateContext(m);syncOutputs();renderCards();updatePrediction();$('lab').scrollIntoView({behavior:'smooth',block:'center'})}
function syncOutputs(){$('homeFormOutput').textContent=$('homeForm').value;$('awayFormOutput').textContent=$('awayForm').value;$('tempoOutput').textContent=$('tempo').value}
function renderMarket(a,model,m){let labels=['主胜','平局','客胜'];if(!a){$('marketMargin').textContent='盘口未核验';$('marketRows').innerHTML=labels.map((l,i)=>`<div><strong>${l}</strong><span>${(model[i]*100).toFixed(1)}%</span><span>—</span><span>—</span><span>—</span></div>`).join('');return}$('marketMargin').textContent=`市场水位 ${(a.overround*100).toFixed(1)}% · ${oddsSource(m)}`;$('marketRows').innerHTML=labels.map((l,i)=>{let e=a.edges[i]*100;return`<div><strong>${l}</strong><span>${(model[i]*100).toFixed(1)}%</span><span>${(a.market[i]*100).toFixed(1)}%</span><span class="${e>0?'positive':e<0?'negative':''}">${e>=0?'+':''}${e.toFixed(1)}pp</span><span>${(a.kelly[i]*100).toFixed(1)}%</span></div>`}).join('')}
function updatePrediction(){let m=matches[selectedIndex],hf=+$('homeForm').value,af=+$('awayForm').value,tp=+$('tempo').value,rho=+$('rho').value/100,crowd={enabled:$('crowdMode').checked,score:`${+$('crowdHome').value||0}:${+$('crowdAway').value||0}`,penalty:+$('crowdPenalty').value/100},raw=simulate(m,hf,af,tp,rho,crowd,50000,20260624+selectedIndex*997+simulationEpoch*7919+hf*31+af*17+tp),ma=odds(m)?marketAnalysis([raw.homeWin,raw.draw,raw.awayWin],odds(m)):null,adj=blendPm(blendMarket(raw,ma),pmAnalysis(m)),market=odds(m)?marketAnalysis([adj.homeWin,adj.draw,adj.awayWin],odds(m)):null,wdl=recWdl(m,adj),hc=recHandicap(m,raw);$('resultCard').animate([{transform:'translateY(5px)',opacity:.75},{transform:'translateY(0)',opacity:1}],{duration:320,easing:'ease-out'});$('homeScore').textContent=raw.best.h;$('awayScore').textContent=raw.best.a;$('predictionType').textContent='模型综合预测';$('homeWin').textContent=`${Math.round(adj.homeWin*100)}%`;$('draw').textContent=`${Math.round(adj.draw*100)}%`;$('awayWin').textContent=`${Math.round(adj.awayWin*100)}%`;$('wdlPick').textContent=wdl.label;$('wdlPickNote').textContent=`${wdl.note} · ${(wdl.probability*100).toFixed(1)}%`;$('handicapPick').textContent=hc.label;$('handicapPickNote').textContent=`${hc.note} · ${(hc.probability*100).toFixed(1)}%`;$('confidence').textContent=`置信度 ${adj.confidence}%`;$('reason').textContent=reason(m,raw,adj);$('xgText').textContent=`${raw.homeXg.toFixed(2)} — ${raw.awayXg.toFixed(2)}`;$('simulationCount').textContent=`${raw.runs.toLocaleString('zh-CN')} 次模拟`;$('rhoOutput').textContent=rho.toFixed(2);$('crowdPenaltyOutput').textContent=`${Math.round(crowd.penalty*100)}%`;$('topScores').innerHTML=raw.topScores.map((x,i)=>`<span><i>${i+1}</i>${x.score}<small>${(x.probability*100).toFixed(1)}%</small></span>`).join('');$('topTotals').innerHTML=raw.topTotals.map((x,i)=>`<span><i>${i+1}</i><strong>${x.goals} 球</strong><small>${(x.probability*100).toFixed(1)}%</small></span>`).join('');let total=raw.homeXg+raw.awayXg;$('homeXgBar').style.width=`${raw.homeXg/total*100}%`;$('awayXgBar').style.width=`${raw.awayXg/total*100}%`;renderMarket(market,[adj.homeWin,adj.draw,adj.awayWin],m)}
['homeForm','awayForm','tempo'].forEach(id=>$(id).addEventListener('input',()=>{syncOutputs();updatePrediction()}));['rho','oddsHome','oddsDraw','oddsAway','crowdHome','crowdAway','crowdPenalty'].forEach(id=>$(id).addEventListener('input',updatePrediction));$('crowdMode').addEventListener('change',updatePrediction);$('predictButton').addEventListener('click',()=>{simulationEpoch++;updatePrediction();$('simulationDoneDialog').showModal()});$('aboutButton').addEventListener('click',()=>$('aboutDialog').showModal());$('closeDialog').addEventListener('click',()=>$('aboutDialog').close());$('simulationDoneButton').addEventListener('click',()=>$('simulationDoneDialog').close());$('aboutDialog').addEventListener('click',e=>{if(e.target===$('aboutDialog'))$('aboutDialog').close()});$('simulationDoneDialog').addEventListener('click',e=>{if(e.target===$('simulationDoneDialog'))$('simulationDoneDialog').close()});
selectedIndex=ranked()[0].index;let m=matches[selectedIndex];$('homeFlag').textContent=m.homeFlag;$('awayFlag').textContent=m.awayFlag;$('homeName').textContent=m.home;$('awayName').textContent=m.away;$('homeForm').value=m.formH;$('awayForm').value=m.formA;setOdds(m);updateContext(m);syncOutputs();renderCards();updatePrediction();
